export const cryptoList = [
    { "id": "1182", "symbol": "BTC", "name": "Bitcoin", "imageUrl": "https://www.cryptocompare.com/media/19633/btc.png" },
    { "id": "7605", "symbol": "ETH", "name": "Ethereum", "imageUrl": "https://www.cryptocompare.com/media/20646/eth_logo.png" },
    { "id": "3808", "symbol": "LTC", "name": "Litecoin", "imageUrl": "https://www.cryptocompare.com/media/19782/litecoin-logo.png" },
    { "id": "3807", "symbol": "DASH", "name": "Dash", "imageUrl": "https://www.cryptocompare.com/media/33842920/dash.png" },
    { "id": "5038", "symbol": "XMR", "name": "Monero", "imageUrl": "https://www.cryptocompare.com/media/19969/xmr.png" },
    { "id": "1183", "symbol": "NXT", "name": "Nxt", "imageUrl": "https://www.cryptocompare.com/media/20627/nxt.png" },
    { "id": "5324", "symbol": "ETC", "name": "Ethereum Classic", "imageUrl": "https://www.cryptocompare.com/media/33752295/etc_new.png" },
    { "id": "4432", "symbol": "DOGE", "name": "Dogecoin", "imageUrl": "https://www.cryptocompare.com/media/19684/doge.png" },
    { "id": "24854", "symbol": "ZEC", "name": "ZCash", "imageUrl": "https://www.cryptocompare.com/media/351360/zec.png" },
    { "id": "5039", "symbol": "BTS", "name": "Bitshares", "imageUrl": "https://www.cryptocompare.com/media/20705/bts.png" },
    { "id": "4430", "symbol": "DGB", "name": "DigiByte", "imageUrl": "https://www.cryptocompare.com/media/12318264/7638-nty_400x400.jpg" },
    { "id": "5031", "symbol": "XRP", "name": "XRP", "imageUrl": "https://www.cryptocompare.com/media/34477776/xrp.png" },
    { "id": "4400", "symbol": "BTCD", "name": "BitcoinDark", "imageUrl": "https://www.cryptocompare.com/media/19630/btcd_1.png" },
    { "id": "2349", "symbol": "PPC", "name": "PeerCoin", "imageUrl": "https://www.cryptocompare.com/media/19864/peercoin-logo.png" },
    { "id": "4425", "symbol": "CRAIG", "name": "CraigsCoin", "imageUrl": "https://www.cryptocompare.com/media/20022/craig.png" },
    { "id": "5023", "symbol": "XBS", "name": "Bitstake", "imageUrl": "https://www.cryptocompare.com/media/351060/xbs_1.png" },
    { "id": "5030", "symbol": "XPY", "name": "PayCoin", "imageUrl": "https://www.cryptocompare.com/media/20076/xpy_1.png" },
    { "id": "3638", "symbol": "PRC", "name": "ProsperCoin", "imageUrl": "https://www.cryptocompare.com/media/20393/prc.png" },
    { "id": "3639", "symbol": "YBC", "name": "YbCoin", "imageUrl": "https://www.cryptocompare.com/media/19975/ybc.png" },
    { "id": "3640", "symbol": "DANK", "name": "DarkKush", "imageUrl": "https://www.cryptocompare.com/media/20247/dank.png" },
    { "id": "3641", "symbol": "GIVE", "name": "GiveCoin", "imageUrl": "https://www.cryptocompare.com/media/20297/give.png" },
    { "id": "3642", "symbol": "KOBO", "name": "KoboCoin", "imageUrl": "https://www.cryptocompare.com/media/20329/kobo.png" },
    { "id": "3643", "symbol": "DT", "name": "DarkToken", "imageUrl": "https://www.cryptocompare.com/media/20031/dt.png" },
    { "id": "3644", "symbol": "CETI", "name": "CETUS Coin", "imageUrl": "https://www.cryptocompare.com/media/20228/ceti.png" },
    { "id": "3645", "symbol": "SUP", "name": "Supcoin", "imageUrl": "https://www.cryptocompare.com/media/20442/sup.png" },
    { "id": "3646", "symbol": "XPD", "name": "PetroDollar", "imageUrl": "https://www.cryptocompare.com/media/20162/xpd.png" },
    { "id": "3647", "symbol": "GEO", "name": "GeoCoin", "imageUrl": "https://www.cryptocompare.com/media/20292/geo.png" },
    { "id": "3648", "symbol": "CHASH", "name": "CleverHash", "imageUrl": "https://www.cryptocompare.com/media/20231/chash.png" },
    { "id": "3649", "symbol": "SPR", "name": "Spreadcoin", "imageUrl": "https://www.cryptocompare.com/media/20438/spr.png" },
    { "id": "3650", "symbol": "NXTI", "name": "NXTI", "imageUrl": "https://www.cryptocompare.com/media/20376/nxti.png" },
    { "id": "3653", "symbol": "WOLF", "name": "Insanity Coin", "imageUrl": "https://www.cryptocompare.com/media/20559/wolf.png" },
    { "id": "3655", "symbol": "XDP", "name": "DogeParty", "imageUrl": "https://www.cryptocompare.com/media/20560/xdp.png" },
    { "id": "3744", "symbol": "2015", "name": "2015 coin", "imageUrl": "https://www.cryptocompare.com/media/20180/2015.png" },
    { "id": "4321", "symbol": "42", "name": "42 Coin", "imageUrl": "https://www.cryptocompare.com/media/12318415/42.png" },
    { "id": "4322", "symbol": "AC", "name": "Asia Coin", "imageUrl": "https://www.cryptocompare.com/media/19593/ac.png" },
    { "id": "4323", "symbol": "ACOIN", "name": "ACoin", "imageUrl": "https://www.cryptocompare.com/media/20079/acoin.png" },
    { "id": "4324", "symbol": "AERO", "name": "Aero Coin", "imageUrl": "https://www.cryptocompare.com/media/19594/aero.png" },
    { "id": "4325", "symbol": "ALF", "name": "AlphaCoin", "imageUrl": "https://www.cryptocompare.com/media/19600/alf.png" },
    { "id": "4326", "symbol": "AGS", "name": "Aegis", "imageUrl": "https://www.cryptocompare.com/media/19595/ags.png" },
    { "id": "4327", "symbol": "AMC", "name": "AmericanCoin", "imageUrl": "https://www.cryptocompare.com/media/19601/amc.png" },
    { "id": "4328", "symbol": "ALN", "name": "AlienCoin", "imageUrl": "https://www.cryptocompare.com/media/20080/aln.png" },
    { "id": "4330", "symbol": "APEX", "name": "ApexCoin", "imageUrl": "https://www.cryptocompare.com/media/19599/apex.png" },
    { "id": "4331", "symbol": "ARCH", "name": "ArchCoin", "imageUrl": "https://www.cryptocompare.com/media/20085/arch.png" },
    { "id": "4371", "symbol": "ARG", "name": "Argentum", "imageUrl": "https://www.cryptocompare.com/media/19602/arg.png" },
    { "id": "4332", "symbol": "ARI", "name": "AriCoin", "imageUrl": "https://www.cryptocompare.com/media/20082/ari.png" },
    { "id": "4333", "symbol": "AUR", "name": "Aurora Coin", "imageUrl": "https://www.cryptocompare.com/media/19608/aur.png" },
    { "id": "4334", "symbol": "AXR", "name": "AXRON", "imageUrl": "https://www.cryptocompare.com/media/20086/axr.png" },
    { "id": "4335", "symbol": "BCX", "name": "BattleCoin", "imageUrl": "https://www.cryptocompare.com/media/19620/bcx.png" },
    { "id": "4337", "symbol": "BET", "name": "BetaCoin", "imageUrl": "https://www.cryptocompare.com/media/19621/bet.png" },
    { "id": "4338", "symbol": "BITB", "name": "BitBean", "imageUrl": "https://www.cryptocompare.com/media/350879/bitb.png" },
    { "id": "4340", "symbol": "BLU", "name": "BlueCoin", "imageUrl": "https://www.cryptocompare.com/media/19624/blu.png" },
    { "id": "4339", "symbol": "BLK", "name": "BlackCoin", "imageUrl": "https://www.cryptocompare.com/media/351795/blk.png" },
    { "id": "4342", "symbol": "BOST", "name": "BoostCoin", "imageUrl": "https://www.cryptocompare.com/media/19626/bost.png" },
    { "id": "4343", "symbol": "BQC", "name": "BQCoin", "imageUrl": "https://www.cryptocompare.com/media/19631/bqc.png" },
    { "id": "4345", "symbol": "XMY", "name": "MyriadCoin", "imageUrl": "https://www.cryptocompare.com/media/19815/myr.png" },
    { "id": "4346", "symbol": "MOON", "name": "MoonCoin", "imageUrl": "https://www.cryptocompare.com/media/19802/moon.png" },
    { "id": "4347", "symbol": "ZET", "name": "ZetaCoin", "imageUrl": "https://www.cryptocompare.com/media/19993/zet.png" },
    { "id": "4348", "symbol": "SXC", "name": "SexCoin", "imageUrl": "https://www.cryptocompare.com/media/19924/sxc.png" },
    { "id": "4349", "symbol": "QTL", "name": "Quatloo", "imageUrl": "https://www.cryptocompare.com/media/19879/qtl.png" },
    { "id": "4350", "symbol": "ENRG", "name": "EnergyCoin", "imageUrl": "https://www.cryptocompare.com/media/19697/enrg.png" },
    { "id": "4351", "symbol": "QRK", "name": "QuarkCoin", "imageUrl": "https://www.cryptocompare.com/media/19882/qrk.png" },
    { "id": "4352", "symbol": "RIC", "name": "Riecoin", "imageUrl": "https://www.cryptocompare.com/media/19888/ric.jpg" },
    { "id": "4353", "symbol": "DGC", "name": "DigiCoin", "imageUrl": "https://www.cryptocompare.com/media/19676/dgc.png" },
    { "id": "4354", "symbol": "LIMX", "name": "LimeCoinX", "imageUrl": "https://www.cryptocompare.com/media/19769/limx.png" },
    { "id": "4399", "symbol": "BTB", "name": "BitBar", "imageUrl": "https://www.cryptocompare.com/media/20083/bitb.png" },
    { "id": "4406", "symbol": "CAIX", "name": "CAIx", "imageUrl": "https://www.cryptocompare.com/media/20226/caix.png" },
    { "id": "4401", "symbol": "BTE", "name": "ByteCoin", "imageUrl": "https://www.cryptocompare.com/media/19632/bte.png" },
    { "id": "4403", "symbol": "BTM", "name": "BitMark", "imageUrl": "https://www.cryptocompare.com/media/20084/btm.png" },
    { "id": "4404", "symbol": "BUK", "name": "CryptoBuk", "imageUrl": "https://www.cryptocompare.com/media/19637/buk.png" },
    { "id": "4405", "symbol": "CACH", "name": "Cachecoin", "imageUrl": "https://www.cryptocompare.com/media/19642/cach.png" },
    { "id": "4407", "symbol": "CANN", "name": "CannabisCoin", "imageUrl": "https://www.cryptocompare.com/media/20015/cann.png" },
    { "id": "4408", "symbol": "CAP", "name": "BottleCaps", "imageUrl": "https://www.cryptocompare.com/media/20017/cap.png" },
    { "id": "4409", "symbol": "CASH", "name": "CashCoin", "imageUrl": "https://www.cryptocompare.com/media/20016/cash.png" },
    { "id": "4410", "symbol": "CAT1", "name": "Catcoin", "imageUrl": "https://www.cryptocompare.com/media/19644/cat.png" },
    { "id": "4411", "symbol": "CBX", "name": "CryptoBullion", "imageUrl": "https://www.cryptocompare.com/media/30001996/cbx.png" },
    { "id": "4412", "symbol": "CCN", "name": "CannaCoin", "imageUrl": "https://www.cryptocompare.com/media/19643/ccn.png" },
    { "id": "4413", "symbol": "CIN", "name": "CinderCoin", "imageUrl": "https://www.cryptocompare.com/media/20698/cinder.png" },
    { "id": "4414", "symbol": "CINNI", "name": "CINNICOIN", "imageUrl": "https://www.cryptocompare.com/media/19651/cinni.jpeg" },
    { "id": "4415", "symbol": "CXC", "name": "CheckCoin", "imageUrl": "https://www.cryptocompare.com/media/20246/cxc.png" },
    { "id": "4416", "symbol": "CLAM", "name": "CLAMS", "imageUrl": "https://www.cryptocompare.com/media/20020/clam.png" },
    { "id": "4417", "symbol": "CLOAK", "name": "CloakCoin", "imageUrl": "https://www.cryptocompare.com/media/19994/cloak.png" },
    { "id": "4418", "symbol": "CLR", "name": "CopperLark", "imageUrl": "https://www.cryptocompare.com/media/19657/clr.png" },
    { "id": "4419", "symbol": "CMC", "name": "CosmosCoin", "imageUrl": "https://www.cryptocompare.com/media/20019/cmc.png" },
    { "id": "4420", "symbol": "CNC", "name": "ChinaCoin", "imageUrl": "https://www.cryptocompare.com/media/20021/cnc.png" },
    { "id": "4421", "symbol": "CNL", "name": "ConcealCoin", "imageUrl": "https://www.cryptocompare.com/media/20024/cnl.png" },
    { "id": "4422", "symbol": "COMM", "name": "Community Coin", "imageUrl": "https://www.cryptocompare.com/media/19661/comm.png" },
    { "id": "4423", "symbol": "COOL", "name": "CoolCoin", "imageUrl": "https://www.cryptocompare.com/media/19658/cool.png" },
    { "id": "4424", "symbol": "CRACK", "name": "CrackCoin", "imageUrl": "https://www.cryptocompare.com/media/20023/crack.png" },
    { "id": "4427", "symbol": "CRYPT", "name": "CryptCoin", "imageUrl": "https://www.cryptocompare.com/media/19664/crypt.png" },
    { "id": "4428", "symbol": "CSC", "name": "CasinoCoin", "imageUrl": "https://www.cryptocompare.com/media/34478059/csc.png" },
    { "id": "4429", "symbol": "DEM", "name": "eMark", "imageUrl": "https://www.cryptocompare.com/media/20028/dem.png" },
    { "id": "4431", "symbol": "DMD", "name": "Diamond", "imageUrl": "https://www.cryptocompare.com/media/19680/dmd.png" },
    { "id": "4433", "symbol": "XVG", "name": "Verge", "imageUrl": "https://www.cryptocompare.com/media/12318032/xvg.png" },
    { "id": "4434", "symbol": "DRKC", "name": "DarkCash", "imageUrl": "https://www.cryptocompare.com/media/20027/drkc.png" },
    { "id": "4435", "symbol": "DSB", "name": "DarkShibe", "imageUrl": "https://www.cryptocompare.com/media/20034/dsb.png" },
    { "id": "4436", "symbol": "DVC", "name": "DevCoin", "imageUrl": "https://www.cryptocompare.com/media/20563/dvc.png" },
    { "id": "4437", "symbol": "EAC", "name": "EarthCoin", "imageUrl": "https://www.cryptocompare.com/media/19690/eac.png" },
    { "id": "4438", "symbol": "EFL", "name": "E-Gulden", "imageUrl": "https://www.cryptocompare.com/media/19692/efl.png" },
    { "id": "4439", "symbol": "ELC", "name": "Elacoin", "imageUrl": "https://www.cryptocompare.com/media/19694/elc.png" },
    { "id": "4440", "symbol": "EMC2", "name": "Einsteinium", "imageUrl": "https://www.cryptocompare.com/media/20033/emc2.png" }
]