export const CHANGE_SEARCH_FILTER = 'CHANGE_SEARCH_FILTER';
export const CHANGE_ELEMENTS_PER_PAGE = 'CHANGE_ELEMENTS_PER_PAGE';
export const CHANGE_OFFSET = 'CHANGE_OFFSET';
export const REQUEST_LIST = 'REQUEST_LIST';
export const RECEIVED_LIST = 'RECEIVED_LIST';
export const SET_CRYPTO = 'SET_CRYPTO';
export const GET_CURRENT_PRICE = 'GET_CURRENT_PRICE';
export const REVEIVED_CHART_DATA = 'REVEIVED_CHART_DATA';
